[2025-03-21T14:48:23.779+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_ingestion_gcs_dag.create_external_cards_table manual__2025-03-21T14:48:05.366198+00:00 [queued]>
[2025-03-21T14:48:23.800+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_ingestion_gcs_dag.create_external_cards_table manual__2025-03-21T14:48:05.366198+00:00 [queued]>
[2025-03-21T14:48:23.800+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-21T14:48:23.825+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_cards_table> on 2025-03-21 14:48:05.366198+00:00
[2025-03-21T14:48:23.838+0000] {standard_task_runner.py:57} INFO - Started process 625 to run task
[2025-03-21T14:48:23.847+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_ingestion_gcs_dag', 'create_external_cards_table', 'manual__2025-03-21T14:48:05.366198+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/etl_ingest_tables.py', '--cfg-path', '/tmp/tmp0hu2iw7d']
[2025-03-21T14:48:23.855+0000] {standard_task_runner.py:85} INFO - Job 190: Subtask create_external_cards_table
[2025-03-21T14:48:23.947+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_ingestion_gcs_dag.create_external_cards_table manual__2025-03-21T14:48:05.366198+00:00 [running]> on host 76faeac9fcab
[2025-03-21T14:48:24.134+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dimension_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_cards_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T14:48:05.366198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T14:48:05.366198+00:00'
[2025-03-21T14:48:24.139+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-21T14:48:24.140+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-21T14:48:24.142+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-21T14:48:24.686+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dimension_ingestion_gcs_dag, task_id=create_external_cards_table, execution_date=20250321T144805, start_date=20250321T144823, end_date=20250321T144824
[2025-03-21T14:48:24.745+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-21T14:48:24.826+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
