[2025-03-21T15:26:20.190+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.create_external_transaction_table manual__2025-03-21T15:23:06.598075+00:00 [queued]>
[2025-03-21T15:26:20.214+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.create_external_transaction_table manual__2025-03-21T15:23:06.598075+00:00 [queued]>
[2025-03-21T15:26:20.216+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-21T15:26:20.250+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_transaction_table> on 2025-03-21 15:23:06.598075+00:00
[2025-03-21T15:26:20.266+0000] {standard_task_runner.py:57} INFO - Started process 1480 to run task
[2025-03-21T15:26:20.274+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trnsaction_ingestion_gcs_dag', 'create_external_transaction_table', 'manual__2025-03-21T15:23:06.598075+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/etl_trsction_table.py', '--cfg-path', '/tmp/tmpkh9h192q']
[2025-03-21T15:26:20.282+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask create_external_transaction_table
[2025-03-21T15:26:20.390+0000] {task_command.py:415} INFO - Running <TaskInstance: trnsaction_ingestion_gcs_dag.create_external_transaction_table manual__2025-03-21T15:23:06.598075+00:00 [running]> on host 76faeac9fcab
[2025-03-21T15:26:20.567+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trnsaction_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_external_transaction_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T15:23:06.598075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T15:23:06.598075+00:00'
[2025-03-21T15:26:20.572+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-21T15:26:20.573+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-21T15:26:20.575+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-21T15:26:21.000+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trnsaction_ingestion_gcs_dag, task_id=create_external_transaction_table, execution_date=20250321T152306, start_date=20250321T152620, end_date=20250321T152621
[2025-03-21T15:26:21.052+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-21T15:26:21.089+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
