[2025-03-20T15:49:33.600+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.gcs_object_exists_task manual__2025-03-20T15:47:08.809308+00:00 [queued]>
[2025-03-20T15:49:33.627+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trnsaction_ingestion_gcs_dag.gcs_object_exists_task manual__2025-03-20T15:47:08.809308+00:00 [queued]>
[2025-03-20T15:49:33.628+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-20T15:49:33.666+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists_task> on 2025-03-20 15:47:08.809308+00:00
[2025-03-20T15:49:33.682+0000] {standard_task_runner.py:57} INFO - Started process 9228 to run task
[2025-03-20T15:49:33.692+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trnsaction_ingestion_gcs_dag', 'gcs_object_exists_task', 'manual__2025-03-20T15:47:08.809308+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/etl_trsction_table.py', '--cfg-path', '/tmp/tmpjn6plj0m']
[2025-03-20T15:49:33.701+0000] {standard_task_runner.py:85} INFO - Job 119: Subtask gcs_object_exists_task
[2025-03-20T15:49:33.817+0000] {task_command.py:415} INFO - Running <TaskInstance: trnsaction_ingestion_gcs_dag.gcs_object_exists_task manual__2025-03-20T15:47:08.809308+00:00 [running]> on host 2c8eeef746cb
[2025-03-20T15:49:34.041+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trnsaction_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='gcs_object_exists_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T15:47:08.809308+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T15:47:08.809308+00:00'
[2025-03-20T15:49:34.045+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:49:34.048+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-20T15:49:34.049+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:49:34.051+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:50:34.307+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:50:34.309+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:50:34.310+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:51:34.542+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:51:34.544+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:51:34.545+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:52:34.774+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:52:34.776+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:52:34.777+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:53:35.005+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:53:35.006+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:53:35.008+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:54:35.230+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:54:35.232+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:54:35.233+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:55:35.466+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:55:35.469+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:55:35.470+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:56:35.744+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:56:35.746+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:56:35.747+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:57:35.983+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:57:35.985+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:57:35.986+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:58:36.222+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:58:36.225+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:58:36.227+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T15:59:36.486+0000] {gcs.py:93} INFO - Sensor checks existence of : financial_transaction-bucket, /opt/***/temp_data/trnsction/trnsction
[2025-03-20T15:59:36.489+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-20T15:59:36.490+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-03-20T16:00:28.947+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-20T16:00:28.953+0000] {process_utils.py:131} INFO - Sending 15 to group 9228. PIDs of all processes in the group: [9228]
[2025-03-20T16:00:28.953+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 9228
[2025-03-20T16:00:28.954+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-20T16:00:29.047+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9228, status='terminated', exitcode=0, started='15:49:32') (9228) terminated with exit code 0
